### ISSUE TITLE
Leap Year

### ISSUE THREAD

**Issue by Tyree** [NickBusey/jQuery-Date-Select-Boxes-Plugin#5]
I know this is obviously an old plugin, but I'm hoping someone is still watching the issues.

Being 2020, leap year, I'm noticing the leap year function isn't filling the proper amount of days for February.

Thanks!

**Comment by NickBusey** [comment]
Under 'Generated Tags' on this page http://nickbusey.github.io/jQuery-Date-Select-Boxes-Plugin/ if I click February it shows 29 days for 2020. I believe that is correct, what behavior are you seeing?

**Comment by Tyree** [comment]
Weird. When I tried it, it only showed 28 days for February. Same for 2016. I doctored the function that checks for leap year, and changed all the `===` to `==` and that fixed it (to match other leap year detection code I found online). But, if it's working for you with as-is, I'm not sure what's going on.
